### ISSUE TITLE
Generation with custom samples

### ISSUE THREAD

**Issue by TommasoBorghesi612** [Gariscat/loopy#1]
Hi, first thank you for the amazing work, i herad thw sample you have on you demo page and it sounds really good.

I tried to run the file demo.py but i realized i was missing all the samples Ultrasonic-...-.wav, so i downloaded some other samples of the same instruments (leads, pads, kicks etc) and tried to run you code again changing the references.
But i get this error:

Traceback (most recent call last):
  File "demo.py", line 223, in <module>
    track.save_audio(save_name=f'prog_{i}', target_dir='../renders')
  File "C:\Users\tborghesi\Desktop\loopy-master\loopy\track.py", line 151, in save_audio
    sf.write(target_path, self.render(gain), self._sr)
  File "C:\Users\tborghesi\Desktop\loopy-master\loopy\track.py", line 122, in render
    source_y=pattern.render(),
  File "C:\Users\tborghesi\Desktop\loopy-master\loopy\pattern.py", line 120, in render
    return self._channel(self._core.render())
  File "C:\Users\tborghesi\Desktop\loopy-master\loopy\pattern.py", line 86, in render
    note_y = note.render(bpm=self._bpm, sig=self._sig)
  File "C:\Users\tborghesi\Desktop\loopy-master\loopy\generator.py", line 177, in render
    return self._generator.render(
  File "C:\Users\tborghesi\Desktop\loopy-master\loopy\generator.py", line 116, in render
    ret = y * np.expand_dims(e, -1)
ValueError: operands could not be broadcast together with shapes (0,2) (15503,1)

This is due to the fact that my samples are apparently not long enough and when reading them through the parse function only the lists of the first pitches (from A0 to A1) gets filled and the other remains empty, and thus we have the (0,2) shape that gives us the error.

So i was wondering if the code is strongly bounded to the sample that are referenced or if making some simple tweaks i can try to generate with Loopy using custom samples.

And if you can could you please spend a some words explaining how do you go from the waveform of the samples to the generated piece? A simple high level overview is enough and highly appreciated of course, is just that the code is not that easy and understand exactly what is going on is not so immediate.

In any case thank you and have a nice day.

**Comment by Gariscat** [comment]
Hi, thank you SO much for your feedback!

I wish I could check the errors right away but I am busy polishing the
technical paper to be resubmitted by 4.30. Here are a few suggestions I
have by now:

I have added quite some features to LooPy recently and the repo has been
updated really frequently in the past two weeks (perhaps the bug has been
fixed). Maybe you can try the latest version and see if it works? I intend
to make it versatile so any sample could be loaded into the program. But
still, it might be an issue of truncation?

I would also try to finish the doc by June if it goes well. Thank you again
for trying my package :) If you notice other issues please let me know
directly!

On Thu, 20 Apr 2023 at 8:00 PM TommasoBorghesi612 ***@***.***>
wrote:

> Hi, first thank you for the amazing work, i herad thw sample you have on
> you demo page and it sounds really good.
>
> I tried to run the file demo.py but i realized i was missing all the
> samples Ultrasonic-...-.wav, so i downloaded some other samples of the same
> instruments (leads, pads, kicks etc) and tried to run you code again
> changing the references.
> But i get this error:
>
> Traceback (most recent call last):
> File "demo.py", line 223, in
> track.save_audio(save_name=f'prog_{i}', target_dir='../renders')
> File "C:\Users\tborghesi\Desktop\loopy-master\loopy\track.py", line 151,
> in save_audio
> sf.write(target_path, self.render(gain), self._sr)
> File "C:\Users\tborghesi\Desktop\loopy-master\loopy\track.py", line 122,
> in render
> source_y=pattern.render(),
> File "C:\Users\tborghesi\Desktop\loopy-master\loopy\pattern.py", line 120,
> in render
> return self._channel(self._core.render())
> File "C:\Users\tborghesi\Desktop\loopy-master\loopy\pattern.py", line 86,
> in render
> note_y = note.render(bpm=self._bpm, sig=self._sig)
> File "C:\Users\tborghesi\Desktop\loopy-master\loopy\generator.py", line
> 177, in render
> return self._generator.render(
> File "C:\Users\tborghesi\Desktop\loopy-master\loopy\generator.py", line
> 116, in render
> ret = y * np.expand_dims(e, -1)
> ValueError: operands could not be broadcast together with shapes (0,2)
> (15503,1)
>
> This is due to the fact that my samples are apparently not long enough and
> when reading them through the parse function only the lists of the first
> pitches (from A0 to A1) gets filled and the other remains empty, and thus
> we have the (0,2) shape that gives us the error.
>
> So i was wondering if the code is strongly bounded to the sample that are
> referenced or if making some simple tweaks i can try to generate with Loopy
> using custom samples.
>
> And if you can could you please spend a some words explaining how do you
> go from the waveform of the samples to the generated piece? A simple high
> level overview is enough and highly appreciated of course, is just that the
> code is not that easy and understand exactly what is going on is not so
> immediate.
>
> In any case thank you and have a nice day.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Gariscat_loopy_issues_1&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2V93HzaTdKPxIttDVdQ0hg&m=snJZOOeO3USrD-jehJPLfQrwVLoB5kyBjMekoraH46g6HiBH8eo4tSfFY5Lw-2Yh&s=FfzmLN8HFDwzsHrQQ189McB2nqxiT5kPvGVDPQfkqxs&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ARHTLETWMQHEEV6CYRR7YVDXCFMQZANCNFSM6AAAAAAXFWURWA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2V93HzaTdKPxIttDVdQ0hg&m=snJZOOeO3USrD-jehJPLfQrwVLoB5kyBjMekoraH46g6HiBH8eo4tSfFY5Lw-2Yh&s=x0-YYFdXJGckgJkT-d9NtK3EHJj-GLO2_Fg8FNjxeDc&e=>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>
-- 
Regards,
Xinyu Li

**Comment by TommasoBorghesi612** [comment]
Hi, i saw that you uploaded a google drive link to all the samples, preset etc that you reference in the code so i think i can close this issue.

Thank you and have a nice day.

tommaso
